### ISSUE TITLE
PARTIES

### ISSUE THREAD

**Issue by mprasolov** [LanCoreTeam/LanCore#3]
# Goals
Have a section of the website that allows users to
* Create a party
    * Party Name
    * Party Date (Validation and JSON serialization required)
    * Party Location (Use of validation and JSON serialization debatable)
    * Requirements *What is supposed to be here and what format?*
    * Admin Password (Encryption method is needed)
    * URL (This will be randomly decided, needs to be removed from form)
    * Token (Password to access party attendee view, to be distributed to attendees, *maybe by email/SMS*)
* View their party's dashboard using URL and admin password and be able to change party details
* View the attendee page for the party he/she was invited to

# Tasks
- [x] Setup SQlite database
- [x] Finish party creation form
- [x] Configure JSON serialization/deserialization (if necessary)
- [ ] **Encrypt admin passwords!**
